version: '3.8'

services:
  fronte:
    image: frontend
    container_name: fronte
    ports:
      - 5000:5000

  backe:
    image: backend
    container_name: backe
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    ports:
      - 8080:8080
  redis:
    image: redis
    container_name: redis
    
    restart: unless-stopped
    