version: '3.9'

services:
  fronte:
    image: frontend
    container_name: fronte
    ports:
      - 5000:5000

  backe:
    image: backend
    container_name: backe
    depends_on:
      - redis
      - postgres
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
    ports:
      - 8080:8080
  redis:
    image: redis
    container_name: redis
  
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    restart: unless-stopped
    volumes:
      - ./db_postgres:/var/lib/postgresql/data
volumes:
  db_postgres:
