version: '3.9'

services:
  fronte:
    image: frontend
    container_name: fronte
    ports:
      - 5000:5000

  backe:
    image: back_image
    container_name: backe
    depends_on:
      - redis
      - postgres
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
    ports:
      - 8080:8080

  nginxproxy:
    image: nginx:alpine
    container_name: nginxproxy
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fronte
      - backe

  redis:
    image: redis
    container_name: redis
  
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    restart: unless-stopped
    volumes:
      - ./db_postgres:/var/lib/postgresql/data
volumes:
  db_postgres:
  nginx.conf:
